name: car-detector-backend
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - python-multipart
    - python-jose
    - passlib
    - bcrypt
    - aiofiles
    - python-dotenv
    - Pillow
    - scipy
    - datasets
    - tqdm
